# File: .github/workflows/OIDC_workflow.yml

name: Update CustPOC Subscription with TemplateSpec
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.Azure_CustPOC_Client_ID }}
            tenant-id: ${{ secrets.Azure_CustPOC_Tenant_ID }}
            subscription-id: ${{ secrets.Azure_CustPOC_Subscription_ID }} 
            enable-AzPSSession: true

        - name: 'Update Master templatespec'
          uses: azure/powershell@v1
          with:
             inlineScript: |
              $rgname = "E2-Infra"
              $tempspecName = "Master"
              $region = "EastUS2"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/master/uimaster-v2.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/master/master-v2.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"
       
        - name: 'Update ADForest-DSC templatespec'
          uses: azure/powershell@v1
          with:
             inlineScript: |
              $rgname = "E2-Infra"
              $tempspecName = "ADForest-DSC"
              $region = "EastUS2"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/master/uiadforest.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/master/adforest-dsc.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"
   
        - name: 'Update ADForest-script templatespec'
          uses: azure/powershell@v1
          with:
             inlineScript: |
              $rgname = "E2-Infra"
              $tempspecName = "ADForest-script"
              $region = "EastUS2"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/master/uiadforest.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/master/adforest.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"
   
