# File: .github/workflows/OIDC_workflow.yml

name: Update NonProd Subscription with TemplateSpec
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.Azure_NonProd_Client_ID }}
            tenant-id: ${{ secrets.Azure_NonProd_Tenant_ID }}
            subscription-id: ${{ secrets.Azure_NonProd_Subscription_ID }} 
            enable-AzPSSession: true

        - name: 'Update main templatespec'
          uses: azure/powershell@v1
          with:
             inlineScript: |
              $rgname = "CoreInfrastructure"
              $tempspecName = "main"
              $region = "EastUS"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/ui/ui-vmbuild.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/vmbuild.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"
       
        - name: 'Update ADForest-DSC templatespec'
          uses: azure/powershell@v1
          with:
             inlineScript: |
              $rgname = "CoreInfrastructure"
              $tempspecName = "ADForest-DSC"
              $region = "EastUS"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/ui/ui-adforest.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/adforest-dsc.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"
   
        - name: 'Update ADForest-script templatespec'
          uses: azure/powershell@v1
          with:
             inlineScript: |
              $rgname = "CoreInfrastructure"
              $tempspecName = "ADForest-script"
              $region = "EastUS"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/ui/ui-adforest.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/adforest.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"

        - name: 'Update ADDCPromo-DSC templatespec'
          uses: azure/powershell@v1
          with:
             inlineScript: |
              $rgname = "CoreInfrastructure"
              $tempspecName = "ADDCPromo-DSC"
              $region = "EastUS"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/ui/ui-addcpromo.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/addcpromo-dsc.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"
   
