# File: .github/workflows/OIDC_workflow.yml

name: Update SeanNet Subscription with TemplateSpec
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs: 
  Deploy-Templates:
      runs-on: ubuntu-latest
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.Azure_SeanNet_Client_ID }}
            tenant-id: ${{ secrets.Azure_SeanNet_Tenant_ID }}
            subscription-id: ${{ secrets.Azure_SeanNet_Subscription_ID }} 
            enable-AzPSSession: true

        - name: 'Update VMBuilder templatespec'
          uses: azure/powershell@v2
          with:
             inlineScript: |
              $rgname = "E1-Infra"
              $tempspecName = "VMBuilder"
              $region = "EastUS"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/ui/ui-vmbuild.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/vmbuild.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"

        - name: 'Update AZ-ClusterNodes templatespec'
          uses: azure/powershell@v2
          with:
             inlineScript: |
              $rgname = "E1-Infra"
              $tempspecName = "AZ-ClusterNodes"
              $region = "EastUS"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/ui/ui-azclusternodes.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/azclusternodes.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"

        - name: 'Update ADForest-DSC templatespec'
          uses: azure/powershell@v2
          with:
             inlineScript: |
              $rgname = "E1-Infra"
              $tempspecName = "ADForest-DSC"
              $region = "EastUS"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/ui/ui-adforest.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/adforest-dsc.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"
   
        - name: 'Update ADForest-script templatespec'
          uses: azure/powershell@v2
          with:
             inlineScript: |
              $rgname = "E1-Infra"
              $tempspecName = "ADForest-script"
              $region = "EastUS"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/ui/ui-adforest.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/adforest.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"

        - name: 'Update ADDCPromo-DSC templatespec'
          uses: azure/powershell@v2
          with:
             inlineScript: |
              $rgname = "E1-Infra"
              $tempspecName = "ADDCPromo-DSC"
              $region = "EastUS"
              $uifile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/ui/ui-addcpromo.json
              $templatefile = Invoke-WebRequest -Uri https://raw.githubusercontent.com/SeanGreenbaum/Azure-VMCompute/main/addcpromo-dsc.json
              $date = Get-Date -Format "MMddyy-HHmmss"
              New-AzTemplateSpec -ResourceGroupName $rgname -Name $tempspecName -Version "Refreshed-$date" -Location $region -TemplateJson $templatefile.Content -UIFormDefinitionString $uifile.Content
             azPSVersion: "latest"
   

